#!/bin/sh
# /etc/init.d/radio

# Create a symlink in init.d 
# sudo ln -s /home/mendhak/rpi-internet-radio/radio radio
# Set permissions
# sudo chmod 777 /home/mendhak/rpi-internet-radio/radio
# Install the init script
# sudo update-rc.d radio defaults

PIDFILE=/var/run/rpi-internet-radio.pid


case "$1" in
 start)
 echo "Starting radio "
 start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec "/home/mendhak/rpi-internet-radio/player.py"
 ;;
 stop)
 echo "Stopping radio"
 cat $PIDFILE
 sudo kill -15 `cat $PIDFILE`
 ;;
 *)
 echo "Usage: /etc/init.d/radio {start|stop}"
 exit 1
 ;;
esac
 
exit 0
